version: '2'

services:

    php:
        environment:
            - SYMFONY_ENV=dev
        image: "php"
        build: docker/php
        env_file:
            - .env
        volumes:
            - ./:/var/www/symfony/

    nginx:
        environment:
            - SYMFONY_ENV=dev
        image: "ngnix:latest"
        build: docker/nginx
        env_file:
            - .env
        ports:
            - 81:80
        links:
            - php
        volumes:
            - ./:/var/www/symfony/
    maildev:
        image: djfarrelly/maildev
        ports:
            - 8081:80
volumes:
    db_data: